PORT = 1035
HOST = 0.0.0.0
REACT_APP_MEALDB_API = https://www.themealdb.com/version: 2

updates:
    - package-ecosystem: npm
      directory: "/"
      schedule:
          interval: daily
      open-pull-requests-limit: 10
      labels:
          - dependencies
      versioning-strategy: increase